### PR TITLE
colorstats: do not recompute the histogram/summary-scale unless it is necessary

### PR DESCRIPTION
**Pull request by mbouron**

### CODE REVIEW

**Review by ubitux — COMMENTED** [review]
Should be fine; in what situation does this help? Only when the player is in pause and spamming draw events?

**Comment by mbouron** [comment]
> Should be fine; in what situation does this help? Only when the player is in pause and spamming draw events?

It helps when the player is paused but more importantly it  helps in the scope demo scene where the colorstats draw callback is called by the, renderwaveform (parade), renderwaveform and renderhistogram (so instead of computing 3 times the colorstats data, it does it only once).

**Comment by ubitux** [comment]
> > Should be fine; in what situation does this help? Only when the player is in pause and spamming draw events?
> 
> It helps when the player is paused but more importantly it helps in the scope demo scene where the colorstats draw callback is called by the renderwaveform (parade), renderwaveform and renderhistogram (so instead of computing 3 times the colorstats data, it does it only once).

Is this going to work? (note the interlaced compute)

```mermaid
graph

Group -- 0 --> Render0
Group -- 1 --> Compute
Group -- 2 --> Render1
Compute --> Texture
Render0 --> ColorStats
Render1 --> ColorStats
ColorStats --> Texture
```

**Comment by mbouron** [comment]
> > > Should be fine; in what situation does this help? Only when the player is in pause and spamming draw events?
> > 
> > 
> > It helps when the player is paused but more importantly it helps in the scope demo scene where the colorstats draw callback is called by the renderwaveform (parade), renderwaveform and renderhistogram (so instead of computing 3 times the colorstats data, it does it only once).
> 
> Is this going to work? (note the interlaced compute)

Good catch. I'll come up with a better alternative.

**Comment by mbouron** [comment]
Closing for now until a better solution is found.

**Pull request closed without merging**
